FROM linuxdeepin/deepin:beige-25-loong64-v1.5.0

# 2285
ARG GN_REVISION="81b24e01531ecf0eff12ec9359a555ec3944ec4e"

ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'deb https://mirrors.ustc.edu.cn/deepin/beige beige main commercial community' > /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        build-essential \
        clang-18 \
        python3 \
        ninja-build && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100

WORKDIR /root
RUN git clone https://gn.googlesource.com/gn && \
    cd gn && \
    git checkout ${GN_REVISION} && \
    python3 build/gen.py && \
    ninja -C out && \
    tar czf /root/gn.tar.gz -C out gn
