FROM linuxdeepin/deepin:crimson-loong64-v1.6.0

# Chromium 150 / Electron 43.4.1
ARG GN_REVISION="3357c4f51b1a9e676378c695dd9c7e9911c35ee6"

ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'deb https://mirrors.ustc.edu.cn/deepin/beige crimson main commercial community' > /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        build-essential \
        clang-18 \
        python3 \
        ninja-build && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100

WORKDIR /root
RUN git clone https://gn.googlesource.com/gn && \
    cd gn && \
    git checkout ${GN_REVISION} && \
    python3 build/gen.py && \
    ninja -C out && \
    tar czf /root/gn.tar.gz -C out gn
