FROM linuxdeepin/deepin:crimson-loong64-v1.6.0

ARG LLVM_COMMIT="20b6ec66967ac2a8f932863c1abf251e5b17a843" LLVM_NAME="llvm-23"

ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'deb https://mirrors.ustc.edu.cn/deepin/beige crimson main commercial community' > /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        make \
        pkg-config \
        ninja-build \
        build-essential \
        cmake \
        libxml2-dev \
        libzstd-dev \
        lld-18 \
        python3 \
        zlib1g \
        zlib1g-dev \
        clang-18 && \
    update-alternatives --install /usr/bin/cc cc /usr/bin/clang-18 100 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-18 100

WORKDIR /root
ENV CPP_TRIPLE=loongarch64-linux-gnu \
    LLVM_DEFAULT_TRIPLE=loongarch64-unknown-linux-gnu \
    CFLAGS="-target loongarch64-linux-gnu -mcmodel=medium" \
    CXXFLAGS="-target loongarch64-linux-gnu -mcmodel=medium"
ADD https://github.com/llvm/llvm-project/archive/${LLVM_COMMIT}.tar.gz .
RUN tar xf ${LLVM_COMMIT}.tar.gz && \
    mv llvm-project-${LLVM_COMMIT} llvm-project && \
    cmake -G Ninja /root/llvm-project/llvm \
        -DCMAKE_BUILD_TYPE=Release \
        -DLLVM_ENABLE_ASSERTIONS=ON \
        -DLLVM_ENABLE_IO_SANDBOX=OFF \
        -DLLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra" \
        -DLLVM_ENABLE_RUNTIMES="compiler-rt" \
        -DLLVM_TARGETS_TO_BUILD="AArch64;ARM;LoongArch;Mips;PowerPC;RISCV;SystemZ;WebAssembly;X86" \
        -DLLVM_ENABLE_PIC=ON \
        -DLLVM_ENABLE_Z3_SOLVER=OFF \
        -DCLANG_PLUGIN_SUPPORT=OFF \
        -DCLANG_ENABLE_STATIC_ANALYZER=OFF \
        -DCLANG_ENABLE_ARCMT=OFF \
        -DLLVM_ENABLE_DIA_SDK=OFF \
        -DLLVM_ENABLE_LLD=ON \
        -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON \
        -DLLVM_ENABLE_CURL=OFF \
        -DLIBCLANG_BUILD_STATIC=ON \
        -DLLVM_INSTALL_UTILS=ON \
        -DLLVM_ENABLE_ZSTD=ON \
        -DLLVM_ENABLE_ZLIB=FORCE_ON \
        -DLLVM_ENABLE_LIBXML2=FORCE_ON \
        -DCLANG_ENABLE_LIBXML2=NO \
        -DLLVM_ENABLE_UNWIND_TABLES=OFF \
        -DLLVM_BUILD_DOCS=OFF \
        -DLLVM_INCLUDE_TESTS=OFF \
        -DCMAKE_INSTALL_PREFIX=/usr/lib/${LLVM_NAME} \
        -DLLVM_DEFAULT_TARGET_TRIPLE=${LLVM_DEFAULT_TRIPLE} \
        -DCMAKE_SKIP_RPATH=NO \
        -DCMAKE_SKIP_INSTALL_RPATH=NO && \
    ninja -j32 && \
    DESTDIR=/root/llvm-targets ninja install && \
    tar -czf /root/llvm.tar.gz -C /root/llvm-targets usr
