FROM linuxdeepin/deepin:crimson-loong64-v1.6.0

ARG LIBFFI_VERSION="3.4.6"

ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'deb https://mirrors.ustc.edu.cn/deepin/beige crimson main commercial community' > /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        gcc \
        make \
        autoconf \
        automake \
        libtool \
        pkg-config

WORKDIR /root
RUN curl -LO https://github.com/libffi/libffi/releases/download/v${LIBFFI_VERSION}/libffi-${LIBFFI_VERSION}.tar.gz && \
    tar xf libffi-${LIBFFI_VERSION}.tar.gz

WORKDIR /root/build
RUN /root/libffi-${LIBFFI_VERSION}/configure \
        CFLAGS="-mcmodel=medium" \
        --prefix=/root/build/out \
        --enable-pax_emutramp \
        --enable-static \
        --disable-docs && \
    make libffi_convenience.la && \
    tar czf libffi.tar.gz --directory=.libs .