name: Build Electron

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: 'Stage to run through'
        required: true
        default: 'full'
        options:
          - full
          - build
          - package
      builderImageTag:
        type: string
        required: true
        default: "deepin-23-glibc-238"
        description: Builder image tag
      electronVersion:
        type: string
        required: true
        default: "34.2.0"
        description: Version of electron to build

env:
  ROOT_PATH: /home/builduser/buildroot
  DEPOT_PATH: /home/builduser/.electron_build_tools/third_party/depot_tools
  SRC_PATH: /home/builduser/buildroot/src
  OUT_PATH: /home/builduser/buildroot/src/out/Release
  RELEASE_PATH: /home/builduser/buildroot/release/${{ inputs.electronVersion }}
  ELECTRON_REPO: https://github.com/electron/electron.git
  REPO_PATH: ${{ github.workspace }}

jobs:
  prepare:
    runs-on: [self-hosted, ryustation]
    container:
      image: ghcr.io/darkyzhou/electron-buildtools:latest
      volumes:
        - /mnt/data/build/electron-loong64:/home/builduser
    steps:
      - uses: actions/checkout@v4
      - name: Update Sources
        if: ${{ inputs.stage == 'full' }}
        run: |
          set -ex

          pushd "$ROOT_PATH"
          if [ ! -d "src/electron" ]; then
            # If you encounter platform compatibility errors from depot_tools, apply `depot.patch` as below
            npx e init -i release -r "$ROOT_PATH" electron-loong64
            git clone "$ELECTRON_REPO" src/electron
          fi
          "$REPO_PATH"/scripts/update.sh
          popd
        env:
          ROOT_PATH: ${{ env.ROOT_PATH }}
          ELECTRON_REPO: ${{ env.ELECTRON_REPO }}
          ELECTRON_VERSION: ${{ env.ELECTRON_VERSION }}
          DEPOT_PATH: ${{ env.DEPOT_PATH }}
      - name: Patch Sources
        if: ${{ inputs.stage == 'full' }}
        run: |
          "$REPO_PATH"/scripts/patch.sh
        env:
          ROOT_PATH: ${{ env.ROOT_PATH }}
          REPO_PATH: ${{ env.REPO_PATH }}
      - name: Sync Dependencies
        if: ${{ inputs.stage == 'full' }}
        run: |
          "$REPO_PATH"/scripts/sync.sh
        env:
          ROOT_PATH: ${{ env.ROOT_PATH }}
          REPO_PATH: ${{ env.REPO_PATH }}
          DEPOT_PATH: ${{ env.DEPOT_PATH }}

  build:
    needs: prepare
    runs-on: [self-hosted, ryustation]
    permissions:
      contents: write
      packages: write
    container:
      image: ghcr.io/darkyzhou/electron-builder:${{ inputs.builderImageTag }}
      volumes:
        - /mnt/data/build/electron-loong64:/home/builduser
    steps:
      - name: Prepare Files
        if: ${{ inputs.stage != 'package' }}
        run: |
          "$REPO_PATH"/scripts/binaries.sh
          "$REPO_PATH"/scripts/rollup.sh
        env:
          ROOT_PATH: ${{ env.ROOT_PATH }}
      - name: Build Electron
        if: ${{ inputs.stage != 'package' }}
        run: |
          set -ex
          cd "$SRC_PATH"
          rm -f "$OUT_PATH"/electron
          gn gen "$OUT_PATH" --args="import(\"//electron/build/args/release.gn\")" --script-executable=/usr/bin/python3
          ninja -C "$OUT_PATH" electron
        env:
          CC: clang
          CXX: clang++
          AR: ar
          NM: nm
          RUSTC_BOOTSTRAP: 1
      - name: Package Electron
        run: |
          "$REPO_PATH"/scripts/package.sh ${{ inputs.electronVersion }}
        env:
          ROOT_PATH: ${{ env.ROOT_PATH }}
          OUT_PATH: ${{ env.OUT_PATH }}
      - name: Upload Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.RELEASE_PATH }}/*
          release_name: Electron v${{ inputs.electronVersion }} port for Loong64
          tag: v${{ inputs.electronVersion }}
          file_glob: true
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
