name: Build Libraries

on:
  workflow_dispatch:
    inputs:
      gccVersion:
        type: string
        required: true
        default: "13.3.0"
        description: Gcc version to compile
      libffiVersion:
        type: string
        required: true
        default: "3.4.6"
        description: Libffi version to compile

jobs:
  libgcc:
    runs-on: [self-hosted]
    container:
      image: ghcr.io/darkyzhou/electron-build-runner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build libgcc
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: libgcc:latest
          file: dockerfiles/Dockerfile.libgcc
          context: dockerfiles
          build-args: |
            GCC_VERSION=${{ inputs.gccVersion }}
      - name: Extract libgcc Artifact
        uses: shrink/actions-docker-extract@v3
        with:
          image: libgcc:latest
          path: /root/build/libgcc.tar.gz
          destination: dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libgcc
          path: dist/libgcc.tar.gz

  libffi:
    runs-on: [self-hosted, ryustation]
    container:
      image: ghcr.io/darkyzhou/electron-build-runner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build libffi
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: libffi:latest
          file: dockerfiles/Dockerfile.libffi
          context: dockerfiles
          build-args: |
            GCC_VERSION=${{ inputs.gccVersion }}
      - name: Extract libffi Artifact
        uses: shrink/actions-docker-extract@v3
        with:
          image: libffi:latest
          path: /root/build/libffi.tar.gz
          destination: dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libffi
          path: dist/libffi.tar.gz
